---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: zcashd-androidbuild-
spec:
  workspaces:
    - name: venv
      emptyDir: {}
  resources:
    inputs:
      - name: source
        resourceSpec:
          type: git
          params:
            - name: revision
              value: master
            - name: url
              value: https://github.com/zcash/zcash-android-wallet-sdk
  taskSpec:
    resources:
      inputs:
        - name: source
          type: git
    workspaces:
        - name: venv
          mountPath: /venv
    steps:
      - name: setup-env
        image: electriccoinco/zcash-android-builder:latest
        script: |
          #!/bin/bash
          set -e -o pipefail
          ls ./source
          cd ./source
          ./gradlew ciBuid
 
