---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: zcashd-androidbuild-
spec:
  workspaces:
    - name: venv
      emptyDir: {}
  resources:
    inputs:
      - name: source
        resourceSpec:
          type: git
          params:
            - name: url
              value: https://github.com/zcash/zcash-android-wallet-sdk
  taskSpec:
    resources:
      inputs:
        - name: source
          type: git
    workspaces:
        - name: venv
          mountPath: /venv
    steps:
      - name: setup-env
        image: debian:stretch
        script: |
          #!/bin/bash
          set -e -o pipefail
          pwd
          ls -al
          whoami
          apt-get update -y
          apt-get install -y openjdk-8-jdk cmake curl wget
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo 'export PATH=/root/.cargo/bin:$PATH' >> /root/.bashrc
          export PATH=/root/.cargo/bin:$PATH
          rustup target add armv7-linux-androideabi
          rustup target add aarch64-linux-android
          rustup target add i686-linux-android
          export ANDROID_COMPILE_SDK=`egrep '^[[:blank:]]+compileSdkVersion'  app/build.gradle | awk '{print $2}'`
          echo $ANDROID_SDK_TOOLS
          echo $ANDROID_COMPILE_SDK
          wget --quiet --output-document=/tmp/sdk-tools-linux.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
          unzip /tmp/sdk-tools-linux.zip -d .android
          export ANDROID_HOME=$PWD/.android
          export PATH=$PATH:$PWD/.android/platform-tools/
          echo y | .android/tools/bin/sdkmanager "platform-tools" "platforms;android-${ANDROID_COMPILE_SDK}"
          echo y | .android/tools/bin/sdkmanager "system-images;android-24;default;x86"
      - name: build
        image: debian:stretch
        script: |
          #!/bin/bash
          set -e -o pipefail
          chmod +x ./gradlew
          ./gradlew clean assembleZcashtestnetRelease
  
